### ISSUE TITLE
[Android] Tracking: missed tracking from signing v2

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1246]
**Describe the bug**
1. (see: https://github.com/gnosis/safe/wiki/Tracking)
New param for user_key_imported event
import_type (String): seed or key

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.9.0 -2006rc

**Environment**
prod mainnet
**Additional context**

**Comment by tschubotz** [comment]
Marking this as `major` not because user experience is impaired but because we can't tell if now users add more keys due to due the pk import option. So I think this should be fixed in the next release right away.

**Comment by liliya-soroka** [comment]
Reopened:
I still see user_key_imported for both key and seed 
I am expecting to see
user_key_imported for a private key and user_seed_imported for the seed prise

app version 2.9.0 - debug

**Comment by elgatovital** [comment]
@liliya-soroka where do you get these requirements from

**Comment by liliya-soroka** [comment]
Verified
correct import type is displayed for seed phrase and private key
app version 2.10.0 - 2058rc
